plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
	id 'net.neoforged.moddev' version "${moddev_version}" apply false
}

allprojects {
	version = project.mod_version
	group = project.maven_group

	repositories {
		mavenCentral()
		exclusiveContent {
			forRepository {
				maven {
					name = 'Modrinth'
					url = 'https://api.modrinth.com/maven'
				}
			}
			filter {
				includeGroup 'maven.modrinth'
			}
		}
	}
}
