# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
moddev_version=2.0.141
neoform_version=26.1.2-1
neoforge_version=26.1.2.93
neoforge_loader_version_range=[4,)

# Mod Properties
mod_version=1.0.5
maven_group=tritium.music

# Dependencies
fabric_api_version=0.155.2+26.1.2

lombok_version=1.18.42
mixin_version=0.8.5
gson_version=2.11.0
zxing_version=3.5.3
jna_version=5.14.0
lwjgl_version=3.4.1
