# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17.19
moddev_version=2.0.123
neoform_version=1.21.11-20251209.172050
neoforge_version=21.11.45
neoforge_loader_version_range=[4,)

# Mod Properties
mod_version=1.0.3
maven_group=tritium.music

# Dependencies
fabric_api_version=0.141.6+1.21.11

lombok_version=1.18.42
mixin_version=0.8.5
gson_version=2.11.0
zxing_version=3.5.3
jna_version=5.14.0
lwjgl_version=3.3.3
