plugins {
	id 'java-library'
	id 'net.fabricmc.fabric-loom-remap'
}

base {
	archivesName = "${rootProject.name}-common-${project.minecraft_version}"
}

repositories {
	exclusiveContent {
		forRepository {
			maven {
				name = 'Sponge'
				url = 'https://repo.spongepowered.org/repository/maven-public/'
			}
		}
		filter {
			includeGroup 'org.spongepowered'
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()

	compileOnly "org.projectlombok:lombok:${project.lombok_version}"
	annotationProcessor "org.projectlombok:lombok:${project.lombok_version}"
	compileOnly "org.jspecify:jspecify:${project.jspecify_version}"

	api "com.google.code.gson:gson:${project.gson_version}"
	api "com.google.zxing:core:${project.zxing_version}"
	api "net.java.dev.jna:jna:${project.jna_version}"
	api "net.java.dev.jna:jna-platform:${project.jna_version}"
	api "com.microsoft.onnxruntime:onnxruntime:${project.onnxruntime_version}"
	api "com.tianscar.soundtouch:soundtouch-jni-core:${project.soundtouch_jni_version}"
	runtimeOnly "com.tianscar.soundtouch:soundtouch-jni-javase:${project.soundtouch_jni_version}"

	testImplementation platform('org.junit:junit-bom:5.13.4')
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
	useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
	options.release = 17
	options.encoding = 'UTF-8'
	options.compilerArgs << '-Xmaxerrs' << '2000'
}

java {
	toolchain.languageVersion = JavaLanguageVersion.of(17)
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from(rootProject.files('LICENSE', 'COPYING', 'THIRD_PARTY_NOTICES.md', 'LICENSE_BASIC_PITCH',
			'LICENSE_SOUNDTOUCH', 'LICENSE_SOUNDTOUCH_JNI')) {
		rename { "${it}_${rootProject.name}" }
	}
}
