modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "LGPL-3.0-only"

[[mods]]
modId = "tritium_music"
version = "${version}"
displayName = "Tritium Music"
authors = "IzumiiKonata"
description = '''NetEase Cloud Music player'''

[[mixins]]
config = "tritium-music.mixins.json"

[[dependencies.tritium_music]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.tritium_music]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11]"
ordering = "NONE"
side = "CLIENT"
